version: "3.9"
services:
  db:
    image: postgres:14.6-bullseye
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  # redis:
  #   image: redis
  #   ports:
  #     - ${REDIS_PORT}:6379

volumes:
  pg_data:
    driver: local
