version: '3'

dotenv:
  - ".env"

tasks:
  secret:
    cmds:
      - curl -s https://raw.githubusercontent.com/oursky/devsecops-secret/v1.0/generate-secret.sh \
        | bash -s -- \
          .env.example .env

  db:reset:
    cmds:
      - docker compose down --volume
      - docker compose up -d
      - sleep 3
      - task -d app db:reset

  dev:
    deps:
      - dev:app
      - dev:cloud

  dev:cloud:
    cmds: [docker compose up]

  dev:app:
    dir: app
    cmds: [task dev]

  dep:
    cmds:
      - cd app && pnpm i