# fly.toml app configuration file generated for missmarble-dev on 2023-09-25T09:10:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "missmarble-dev"
primary_region = "iad"

[deploy]
  release_command = "pnpm prisma migrate deploy"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"
