# fly.toml app configuration file generated for missmarble on 2023-09-20T22:49:19+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "missmarble"
primary_region = "hkg"

[deploy]
  release_command = "pnpm prisma migrate deploy"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
