version: '3'

dotenv:
  - "../.env"
  - "./.env"

tasks:
  copy-prisma:
    cp -r ../app/prisma .

  start:
    pnpm start

  dev:
    pnpm dev

  dep:
    deps:
      - copy-prisma
    cmds:
      - pnpm i