version: '3'

dotenv:
  - "../.env"

tasks:
  prisma:
    pnpm prisma {{.CLI_ARGS}}

  db:reset:
    cmds:
      - pnpm prisma generate
      - pnpm prisma db push --force-reset
      - pnpm prisma db seed