version: '3'

dotenv:
  - "../.env"
  - "./.env"

tasks:
  dep:
    pnpm i

  dev:
    pnpm dev

  start:
    pnpm start

  prisma:
    pnpm prisma {{.CLI_ARGS}}

  create-migration:
    pnpm prisma migrate dev

  db:reset:
    cmds:
      - pnpm prisma db push --force-reset
      - pnpm prisma db seed