version: '3'

output: prefixed

tasks:
  setup-env:
    interactive: true
    cmds:
      - cd scheduler && flyctl launch --force-machines --build-only  --copy-config

  decrypt: |
    BLACKBOXDATA=environments/prod/.blackbox blackbox_decrypt_all_files
    blackbox_decrypt_all_files

  shred: |
    BLACKBOXDATA=environments/prod/.blackbox blackbox_shred_all_files
    blackbox_shred_all_files

  deploy:
    cmds:
      - task: decrypt
      - task: deploy:app
      - task: deploy:scheduler
      - task: shred

  deploy:app:
    dir: app
    cmds:
      - vercel deploy --yes --prod --token=$VERCEL_TOKEN ../../..

  deploy:scheduler:
    dir: scheduler
    cmds:
      - flyctl --config {{ .TASKFILE_DIR }}/scheduler/fly.toml secrets import --stage < ../app/.env
      - task -d ../../../scheduler copy-prisma
      - flyctl --config {{ .TASKFILE_DIR }}/scheduler/fly.toml deploy --now --auto-confirm --force-machines --remote-only ../../../scheduler