name: cd

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install asdf & tools
          uses: asdf-vm/actions/install@v2

        - name: Install blackbox
          run:  ${PWD}/.github/tools/install-blackbox.sh

        - name: Install flyctl
          uses: superfly/flyctl-actions/setup-flyctl@1.4

        - name: Install Vercel CLI
          run: npm install --global vercel@latest

        - name: Import GPG keys
          run: |
            echo -e "${BLACKBOX_PUBKEY}" | gpg --import --no-tty --batch --yes
            echo -e "${BLACKBOX_PRIVKEY}" | gpg --import --no-tty --batch --yes
          env:
            BLACKBOX_PUBKEY: ${{ secrets.BLACKBOX_PUBKEY }}
            BLACKBOX_PRIVKEY: ${{ secrets.BLACKBOX_PRIVKEY }}

        - name: Deploy app
          run: task -d environments/${{ inputs.environment }} deploy
          env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}