version: '3'

output: prefixed

tasks:
  setup-env:
    interactive: true
    cmds:
      - cd app && flyctl launch --force-machines --build-only --vm-memory 512 --copy-config

  decrypt: |
    BLACKBOXDATA=environments/dev/.blackbox blackbox_decrypt_all_files
    blackbox_decrypt_all_files

  shred: |
    BLACKBOXDATA=environments/dev/.blackbox blackbox_shred_all_files
    blackbox_shred_all_files

  deploy:
    cmds:
      - task: decrypt
      - task: deploy:app
      - task: shred

  deploy:app:
    dir: app
    cmds:
      - flyctl --config {{ .TASKFILE_DIR }}/app/fly.toml secrets import --stage < .env
      - flyctl --config {{ .TASKFILE_DIR }}/app/fly.toml deploy --now --auto-confirm --force-machines --local-only ../../../app