version: '3'

output: prefixed

env:
  BLACKBOXDATA: environments/dev/.blackbox

tasks:
  setup-env:
    cmds:
      - flyctl launch --config app/fly.toml --force-machines --build-only ../../../app

  decrypt:
    blackbox_decrypt_all_files

  shred:
    blackbox_shred_all_files

  deploy:
    cmds:
      - task: decrypt
      - task: deploy:app
      - task: shred

  deploy:app:
    dir: app
    cmds:
      - flyctl --config {{ .TASKFILE_DIR }}/app/fly.toml secrets import --stage < .env
      - flyctl --config {{ .TASKFILE_DIR }}/app/fly.toml deploy --now --auto-confirm --force-machines --local-only ../../../app